# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Parthib Barua
  email: g00410769@atu.ie
description: "An Interesting Modern C++ Blog"

# Build settings
remote_theme: poole/lanyon
