# Site settings
title: Digital Rain Modern C++ Project Blog
author:
  name: Parthib Barua
  email: g00410769@atu.ie
description: "An interesting blog about modern Digital rain"

# Build settings
remote_theme: jekyll/minima
